### ISSUE TITLE
Where that body and text are coming from? Is that from bodyParser?

### ISSUE THREAD

**Issue by ariebrainware** [impactbyte-learn/code-expressjs#1]
Where ```body``` and ```text``` come from?, is that from bodyParser?
https://github.com/impactbyte-network/learn-expressjs/blob/9c333c5b568cb1315595a6d6cc1e7b0bbc15ef42/todos/index.js#L14

**Comment by mhaidarhanif** [comment]
Yes, `req.body.text` is accessible because of `body-parser` module.
